onlineOrderingSystem/login/urls.py
from django.conf.urls import url
from . import views

app_name = 'login'

urlpatterns = [
    url(r'^login/$', views.userLogin, name="login"),
    url(r'^logout/$', views.userLogout, name='logout'),
    url(r'^$', views.index, name='index'),
]

onlineOrderingSystem/menu/urls.py
from django.conf.urls import url
from . import views

app_name = 'menu'

urlpatterns = [
    url(r'^menu/$', views.menu, name="menu"),
    url(r'^create_meal/$', views.create_meal, name="create_meal"),
    url(r'create_side/$', views.create_side, name="create_side"),
    url(r'create_drink/$', views.create_drink, name="create_drink"),
    url(r'create_topping/$', views.create_topping, name="create_topping"),
    url(r'remove_menu_item/$', views.remove_menu_item, name="remove_menu_item"),
    url(r'remove_side_item/$', views.remove_side_item, name="remove_side_item"),
    url(r'remove_drink_item/$', views.remove_drink_item, name="remove_drink_item"),
    url(r'remove_topping_item/$', views.remove_topping_item, name="remove_topping_item")
    # url(r'remove_side_item/$', views.remove_)
]

onlineOrderingSystem/onlineOrderingSystem/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('tickets.urls')),
    url(r'^', include('login.urls')),
    url(r'^', include('menu.urls')),
    url(r'^', include('register.urls')),
]

onlineOrderingSystem/register/urls.py
from django.conf.urls import url
from . import views

app_name = 'register'

urlpatterns = [
    url(r'^register_user/$', views.register_user, name="register_user"),
]

onlineOrderingSystem/tickets/urls.py
from django.conf.urls import url
from . import views

app_name = 'tickets'

urlpatterns = [
    url(r'^kitchen_view/$', views.kitchen_view, name="kitchen_view"),
    url(r'^fulfill_ticket/(?P<ticketID>[0-9]+)/$', views.fulfill_ticket, name="fulfill_ticket"),
    url(r'^managertickets/$', views.manager_view, name="manager_view"),
]

onlineOrderingSystem/templates/base.html
{% load static %}
{% load tz %}
{% timezone 'EST' %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta http-equiv="refresh" content="15000">
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>{% block title %}{% endblock %}</title>
  <!-- Bootstrap core CSS-->
  <link href="{% static "vendor/bootstrap/css/bootstrap.min.css" %}" rel="stylesheet">
  <!-- Custom fonts for this template-->
  <link href="{% static "vendor/font-awesome/css/font-awesome.min.css" %}" rel="stylesheet" type="text/css">
  <!-- Page level plugin CSS-->
  <link href="{% static "vendor/datatables/dataTables.bootstrap4.css" %}" rel="stylesheet">
  <!-- Custom styles for this template-->
  <link href="{% static "css/sb-admin.css" %}" rel="stylesheet">

  <style type="text/css">{% block style %}{% endblock %}</style>
</head>

<body class="fixed-nav sticky-footer bg-dark" id="page-top">
  <!-- Navigation-->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">
    <a class="navbar-brand" href="{% url 'tickets:manager_view' %}">Tiger Orders</a>
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav navbar-sidenav" id="exampleAccordion">

        <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Tickets">
          <a class="nav-link" href="{% url 'tickets:manager_view' %}">
            <i class="fa fa-fw fa-ticket"></i>
            <span class="nav-link-text">Recent Tickets</span>
          </a>
        </li>
        <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Menu">
          <a class="nav-link" href="{% url 'menu:menu' %}">
            <i class="fa fa-fw fa-cutlery"></i>
            <span class="nav-link-text">Menu Items</span>
          </a>
        </li>
        <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Kitchen Terminal">
          <a class="nav-link" href="{% url 'tickets:kitchen_view' %}">
            <i class="fa fa-fw fa-sticky-note"></i>
            <span class="nav-link-text">View Kitchen Terminal</span>
          </a>
        </li>
        <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Register User">
          <a class="nav-link" href="{% url 'register:register_user' %}">
            <i class="fa fa-fw fa-plus"></i>
            <span class="nav-link-text">Register User</span>
          </a>
        </li>
      </ul>
      <ul class="navbar-nav sidenav-toggler">
        <li class="nav-item">
          <a class="nav-link text-center" id="sidenavToggler">
            <i class="fa fa-fw fa-angle-left"></i>
          </a>
        </li>
      </ul>
      <ul class="navbar-nav ml-auto">

        <li class="nav-item">
          <a class="nav-link" data-toggle="modal" data-target="#exampleModal">
            <i class="fa fa-fw fa-sign-out"></i>Logout</a>
        </li>
      </ul>
    </div>
  </nav>

  <div class="content-wrapper">
    {% block content %}
    {% endblock %}

    <footer class="sticky-footer">
      <div class="container">
        <div class="text-center">
          <small>Copyright © Tiger Orders 2017</small>
        </div>
      </div>
    </footer>
    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
      <i class="fa fa-angle-up"></i>
    </a>
    <!-- Logout Modal-->
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
            <button class="close" type="button" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">×</span>
            </button>
          </div>
          <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
          <div class="modal-footer">
            <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
            <a class="btn btn-primary" href="{% url 'login:logout' %}">Logout</a>
          </div>
        </div>
      </div>
    </div>

    {% block modals %}{% endblock %}

    <!-- Bootstrap core JavaScript-->
    <script src="{% static "vendor/jquery/jquery.min.js" %}"></script>
    <script src="{% static "vendor/bootstrap/js/bootstrap.bundle.min.js" %}"></script>
    <!-- Core plugin JavaScript-->
    <script src="{% static "vendor/jquery-easing/jquery.easing.min.js" %}"></script>
    <!-- Page level plugin JavaScript-->
    <script src="{% static "vendor/datatables/jquery.dataTables.js" %}"></script>
    <script src="{% static "vendor/datatables/dataTables.bootstrap4.js" %}"></script>
    <!-- Custom scripts for all pages-->
    <script src="{% static "js/sb-admin.min.js" %}"></script>
    <!-- Custom scripts for this page-->
    <script src="{% static "js/sb-admin-datatables.min.js" %}"></script>
    <script type="text/javascript">{% block scripts %}{% endblock %}</script>
  </div>
</body>

</html>

{% endtimezone %}